// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCEQT9DbPgwhb6zVZ__tbaVRKltPnuJC1o',
    appId: '1:669354829692:web:127c16b4bb7eee1e3166f9',
    messagingSenderId: '669354829692',
    projectId: 'hobbytracker-2b1e7',
    authDomain: 'hobbytracker-2b1e7.firebaseapp.com',
    storageBucket: 'hobbytracker-2b1e7.firebasestorage.app',
    measurementId: 'G-EPLPNWLZPP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5sKITjeLl7MF87fVwNibEMt7hyfCttH0',
    appId: '1:669354829692:android:0823ccaf7268d1103166f9',
    messagingSenderId: '669354829692',
    projectId: 'hobbytracker-2b1e7',
    storageBucket: 'hobbytracker-2b1e7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDouXnVZdcNnvVfdsHcGKzUueiDVcrHJzg',
    appId: '1:669354829692:ios:a27ef4d15a39285c3166f9',
    messagingSenderId: '669354829692',
    projectId: 'hobbytracker-2b1e7',
    storageBucket: 'hobbytracker-2b1e7.firebasestorage.app',
    iosBundleId: 'com.hobbytracker.hobbyTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDouXnVZdcNnvVfdsHcGKzUueiDVcrHJzg',
    appId: '1:669354829692:ios:a27ef4d15a39285c3166f9',
    messagingSenderId: '669354829692',
    projectId: 'hobbytracker-2b1e7',
    storageBucket: 'hobbytracker-2b1e7.firebasestorage.app',
    iosBundleId: 'com.hobbytracker.hobbyTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCEQT9DbPgwhb6zVZ__tbaVRKltPnuJC1o',
    appId: '1:669354829692:web:e968c36d05bc0ccb3166f9',
    messagingSenderId: '669354829692',
    projectId: 'hobbytracker-2b1e7',
    authDomain: 'hobbytracker-2b1e7.firebaseapp.com',
    storageBucket: 'hobbytracker-2b1e7.firebasestorage.app',
    measurementId: 'G-VVHMTDBLNY',
  );
}
